clear
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Pala\Documents\MATLAB\DTU\Thesis\bagger\atest06\bagfile-_test_thrust.csv
%
% Auto-generated by MATLAB on 18-Jun-2020 16:06:07

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "data"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
thrust = readtable("bagfile-_test_thrust.csv", opts);


%% Clear temporary variables
clear opts

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Pala\Documents\MATLAB\DTU\Thesis\bagger\atest06\bagfile-_test_target.csv
%
% Auto-generated by MATLAB on 18-Jun-2020 16:06:31

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "x", "y", "z"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
target = readtable("bagfile-_test_target.csv", opts);


%% Clear temporary variables
clear opts

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Pala\Documents\MATLAB\DTU\Thesis\bagger\atest06\bagfile-_test_mocap.csv
%
% Auto-generated by MATLAB on 18-Jun-2020 16:07:57

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "seq", "stamp", "frame", "x", "y", "z", "ox", "oy", "oz", "ow"];
opts.VariableTypes = ["double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "frame", "EmptyFieldRule", "auto");

% Import the data
mocap = readtable("bagfile-_test_mocap.csv", opts);


%% Clear temporary variables
clear opts

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Pala\Documents\MATLAB\DTU\Thesis\bagger\atest06\bagfile-_test_kp.csv
%
% Auto-generated by MATLAB on 18-Jun-2020 16:08:13

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "x", "y", "z"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
kp = readtable("bagfile-_test_kp.csv", opts);


%% Clear temporary variables
clear opts

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Pala\Documents\MATLAB\DTU\Thesis\bagger\atest06\bagfile-_test_kill.csv
%
% Auto-generated by MATLAB on 18-Jun-2020 16:08:29

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "data"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
kill = readtable("bagfile-_test_kill.csv", opts);


%% Clear temporary variables
clear opts

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Pala\Documents\MATLAB\DTU\Thesis\bagger\atest06\bagfile-_test_att_in.csv
%
% Auto-generated by MATLAB on 18-Jun-2020 16:09:19

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "seq", "stamp", "frame", "x", "y", "z"];
opts.VariableTypes = ["double", "double", "double", "string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "frame", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "frame", "EmptyFieldRule", "auto");

% Import the data
att_in = readtable("bagfile-_test_att_in.csv", opts);


%% Clear temporary variables
clear opts

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Pala\Documents\MATLAB\DTU\Thesis\bagger\atest06\bagfile-_test_attitude.csv
%
% Auto-generated by MATLAB on 18-Jun-2020 16:09:38

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "seq", "stamp", "frame", "x", "y", "z"];
opts.VariableTypes = ["double", "double", "double", "string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "frame", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "frame", "EmptyFieldRule", "auto");

% Import the data
attitude = readtable("bagfile-_test_attitude.csv", opts);


%% Clear temporary variables
clear opts

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Pala\Documents\MATLAB\DTU\Thesis\bagger\atest06\bagfile-_test_baseline.csv
%
% Auto-generated by MATLAB on 18-Jun-2020 16:10:01

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "data"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
baseline = readtable("bagfile-_test_baseline.csv", opts);


%% Clear temporary variables
clear opts

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Pala\Documents\MATLAB\DTU\Thesis\bagger\atest06\bagfile-_test_erd.csv
%
% Auto-generated by MATLAB on 18-Jun-2020 16:10:15

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "seq", "stamp", "frame", "x", "y", "z"];
opts.VariableTypes = ["double", "double", "double", "string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "frame", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "frame", "EmptyFieldRule", "auto");

% Import the data
erd = readtable("bagfile-_test_erd.csv", opts);


%% Clear temporary variables
clear opts

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Pala\Documents\MATLAB\DTU\Thesis\bagger\atest06\bagfile-_test_eri.csv
%
% Auto-generated by MATLAB on 18-Jun-2020 16:10:39

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "seq", "stamp", "frame", "x", "y", "z"];
opts.VariableTypes = ["double", "double", "double", "string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "frame", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "frame", "EmptyFieldRule", "auto");

% Import the data
eri = readtable("bagfile-_test_eri.csv", opts);


%% Clear temporary variables
clear opts

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Pala\Documents\MATLAB\DTU\Thesis\bagger\atest06\bagfile-_test_err.csv
%
% Auto-generated by MATLAB on 18-Jun-2020 16:10:57

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "seq", "stamp", "frame", "x", "y", "z"];
opts.VariableTypes = ["double", "double", "double", "string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "frame", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "frame", "EmptyFieldRule", "auto");

% Import the data
err = readtable("bagfile-_test_err.csv", opts);


%% Clear temporary variables
clear opts

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Pala\Documents\MATLAB\DTU\Thesis\bagger\atest06\bagfile-_test_health.csv
%
% Auto-generated by MATLAB on 18-Jun-2020 16:11:12

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "gyro", "accel", "mag", "level", "local", "globe", "home", "battery"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
health = readtable("bagfile-_test_health.csv", opts);


%% Clear temporary variables
clear opts

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Pala\Documents\MATLAB\DTU\Thesis\bagger\atest06\bagfile-_test_kd.csv
%
% Auto-generated by MATLAB on 18-Jun-2020 16:11:39

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "x", "y", "z"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
kd = readtable("bagfile-_test_kd.csv", opts);


%% Clear temporary variables
clear opts

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Pala\Documents\MATLAB\DTU\Thesis\bagger\atest06\bagfile-_test_ki.csv
%
% Auto-generated by MATLAB on 18-Jun-2020 16:12:06

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "x", "y", "z"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
ki = readtable("bagfile-_test_ki.csv", opts);


%% Clear temporary variables
clear opts
